name: Build Executable (Cross Platform)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag for this release (e.g. v1.2.3)"
        required: true

env:
  MAIN_SCRIPT: PDFArrangeTool.py
  OUTPUT_NAME: PDFArrangeTool

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Nuitka/Nuitka@2.7.15
          pip install PySide6 PyPDF2 qt-material pypdfium2 pillow

      - name: Build with Nuitka
        shell: bash
        run: |
          mkdir -p build

          # Platform-specific options
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ICON_OPTION="--windows-icon-from-ico=icons/icon.ico"
            OUTPUT_FILE="${{ env.OUTPUT_NAME }}-Windows.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            ICON_OPTION="--macos-app-icon=icons/icon.icns"
            OUTPUT_FILE="${{ env.OUTPUT_NAME }}-macOS"
          fi

          python -m nuitka \
            --standalone \
            --onefile \
            --enable-plugin=pyside6 \
            --nofollow-import-to=tkinter \
            $ICON_OPTION \
            --include-data-dir=theme=theme \
            --include-data-dir=icons=icons \
            --windows-console-mode=disable \
            --output-filename=$OUTPUT_FILE \
            --output-dir=build \
            --lto=no \
            --jobs=2 \
            $MAIN_SCRIPT

          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Zip executable
        run: |
          cd build
          zip "${{ env.OUTPUT_NAME }}-${{ runner.os }}.zip" "${{ env.OUTPUT_FILE }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}-${{ runner.os }}
          path: build/${{ env.OUTPUT_NAME }}-${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display files
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.event.inputs.tag_name }}
          body: |
            Auto-built release for PDF Arrange Tool
            - Cross-platform Nuitka build (Windows/macOS)
            - Triggered manually via workflow_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: dist/*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
